#!/usr/bin/env node
/**
 * End-to-end test for apps generated by @nest-extended/cli (`nest-cli`).
 *
 * For each target database it: generates an app (with auth), generates a CRUD
 * resource, preps the DB, boots the server, then exercises auth + full CRUD
 * over HTTP. Run it after changing the generator or its templates to confirm
 * the *emitted* code still boots and serves working endpoints.
 *
 * Usage (via the npm script, which wires up the TS loader):
 *   yarn test:e2e:generated                 # both DBs (SQLite + Mongoose)
 *   yarn test:e2e:generated --db SQLite      # SQLite only (zero external deps)
 *   yarn test:e2e:generated --db Mongoose    # Mongoose only (needs MongoDB/Docker)
 *
 * Assumes `nest-cli` is on PATH (globally linked). See scripts/e2e/README.md.
 */

import { spawn, spawnSync, type ChildProcess } from 'node:child_process';
import { createConnection } from 'node:net';
import { existsSync, mkdirSync, rmSync, createWriteStream } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const APPS_DIR = path.join(REPO_ROOT, '.e2e-apps');
const DIST_CLI = path.join(REPO_ROOT, 'dist', 'packages', 'cli', 'src', 'index.js');

/**
 * How to invoke the generator. Resolved once at startup:
 *   - a globally-linked `nest-cli` on PATH, or
 *   - the locally-built dist entry run via `node` (built on demand).
 */
let CLI: { cmd: string; prefix: string[] } = { cmd: 'nest-cli', prefix: [] };
const nestCli = (args: string[], opts: Record<string, unknown> = {}): Promise<void> =>
  run(CLI.cmd, [...CLI.prefix, ...args], opts);

const RESOURCE = 'product'; // generated CRUD resource → @Controller('product')
const MONGO_HOST = 'localhost';
const MONGO_PORT = 27017;
const MONGO_CONTAINER = 'nest-e2e-mongo';
const SERVER_READY_TIMEOUT_MS = 90_000;

type DbType = 'SQLite' | 'Mongoose';

interface HttpResult {
  ok: boolean;
  status: number;
  body: unknown;
  error?: unknown;
}

interface RunResult {
  db: DbType;
  status: 'PASS' | 'FAIL' | 'SKIP';
  passed?: number;
  total?: number;
  reason?: string;
}

// ---------------------------------------------------------------------------
// Tiny logging helpers (no deps — ANSI directly)
// ---------------------------------------------------------------------------
const C = {
  reset: '\x1b[0m', red: '\x1b[31m', green: '\x1b[32m',
  yellow: '\x1b[33m', blue: '\x1b[34m', dim: '\x1b[2m', bold: '\x1b[1m',
};
const log = (msg: string): void => console.log(msg);
const info = (msg: string): void => console.log(`${C.blue}${msg}${C.reset}`);
const warn = (msg: string): void => console.log(`${C.yellow}⚠ ${msg}${C.reset}`);
const heading = (msg: string): void => console.log(`\n${C.bold}${C.blue}━━ ${msg} ━━${C.reset}`);

// ---------------------------------------------------------------------------
// Process helpers
// ---------------------------------------------------------------------------

/** Promisified spawn; rejects on non-zero exit. */
function run(cmd: string, args: string[], opts: Record<string, unknown> = {}): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, {
      stdio: 'inherit',
      shell: process.platform === 'win32',
      ...opts,
    });
    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${cmd} ${args.join(' ')} exited with code ${code}`));
    });
  });
}

/** Check whether a binary is resolvable on PATH. */
function hasBinary(bin: string): boolean {
  const which = process.platform === 'win32' ? 'where' : 'which';
  return spawnSync(which, [bin], { stdio: 'ignore' }).status === 0;
}

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

/** TCP probe — resolves true if something is listening on host:port. */
function probeTcp(host: string, port: number, timeoutMs = 1000): Promise<boolean> {
  return new Promise((resolve) => {
    const socket = createConnection({ host, port });
    const done = (ok: boolean): void => {
      socket.destroy();
      resolve(ok);
    };
    socket.setTimeout(timeoutMs);
    socket.once('connect', () => done(true));
    socket.once('timeout', () => done(false));
    socket.once('error', () => done(false));
  });
}

// ---------------------------------------------------------------------------
// HTTP helpers (Node 20+ global fetch)
// ---------------------------------------------------------------------------

interface RequestOptions {
  token?: string;
  body?: unknown;
}

function makeClient(port: number) {
  const base = `http://localhost:${port}`;
  return async function request(
    method: string,
    urlPath: string,
    { token, body }: RequestOptions = {},
  ): Promise<HttpResult> {
    const headers: Record<string, string> = {};
    if (token) headers['Authorization'] = `Bearer ${token}`;
    if (body !== undefined) headers['Content-Type'] = 'application/json';
    let res: Response;
    try {
      res = await fetch(`${base}${urlPath}`, {
        method,
        headers,
        body: body !== undefined ? JSON.stringify(body) : undefined,
      });
    } catch (err) {
      return { ok: false, status: 0, body: null, error: err };
    }
    let parsed: unknown = null;
    const text = await res.text();
    if (text) {
      try { parsed = JSON.parse(text); } catch { parsed = text; }
    }
    return { ok: res.ok, status: res.status, body: parsed };
  };
}

type AnyRecord = Record<string, unknown>;

/** Read the id regardless of Mongo (_id) vs Prisma (id) shape. */
const idOf = (obj: unknown): string | null => {
  const rec = obj as AnyRecord | null | undefined;
  return (rec?._id as string) ?? (rec?.id as string) ?? null;
};

/** Normalize a list response: bare array, or { data: [...] } (paginated). */
const asArray = (body: unknown): AnyRecord[] => {
  if (Array.isArray(body)) return body as AnyRecord[];
  const rec = body as AnyRecord | null | undefined;
  if (rec && Array.isArray(rec.data)) return rec.data as AnyRecord[];
  return [];
};

// ---------------------------------------------------------------------------
// Assertion harness — collects results instead of aborting on first failure
// ---------------------------------------------------------------------------
interface CheckResult {
  label: string;
  passed: boolean;
  detail: string;
}

function makeSuite() {
  const results: CheckResult[] = [];
  return {
    check(label: string, cond: unknown, detail = ''): boolean {
      const passed = !!cond;
      results.push({ label, passed, detail });
      const mark = passed ? `${C.green}✓${C.reset}` : `${C.red}✗${C.reset}`;
      const extra = !passed && detail ? ` ${C.dim}(${detail})${C.reset}` : '';
      log(`    ${mark} ${label}${extra}`);
      return passed;
    },
    get failures(): CheckResult[] {
      return results.filter((r) => !r.passed);
    },
    get total(): number {
      return results.length;
    },
  };
}

// ---------------------------------------------------------------------------
// Server lifecycle
// ---------------------------------------------------------------------------

/** Boot `npm run start` in its own process group; return the child. */
function startServer(appDir: string, port: number, logPath: string): ChildProcess {
  const out = createWriteStream(logPath);
  const child = spawn('npm', ['run', 'start'], {
    cwd: appDir,
    env: { ...process.env, PORT: String(port) },
    stdio: ['ignore', 'pipe', 'pipe'],
    shell: process.platform === 'win32',
    detached: process.platform !== 'win32', // own process group → kill the tree
  });
  child.stdout?.pipe(out);
  child.stderr?.pipe(out);
  return child;
}

/** Poll GET / until the server responds, or time out. */
async function waitForServer(port: number, child: ChildProcess, timeoutMs: number): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (child.exitCode !== null) {
      throw new Error(`server process exited early with code ${child.exitCode}`);
    }
    if (await probeTcp('localhost', port, 1000)) {
      // Port open — give Nest a beat to finish wiring routes.
      await sleep(500);
      return true;
    }
    await sleep(1000);
  }
  return false;
}

function killServer(child: ChildProcess | undefined): void {
  if (!child || child.exitCode !== null || child.pid === undefined) return;
  try {
    if (process.platform !== 'win32') {
      process.kill(-child.pid, 'SIGTERM'); // kill the whole group
    } else {
      spawnSync('taskkill', ['/pid', String(child.pid), '/T', '/F'], { stdio: 'ignore' });
    }
  } catch {
    try { child.kill('SIGKILL'); } catch { /* already gone */ }
  }
}

// ---------------------------------------------------------------------------
// Mongo handling
// ---------------------------------------------------------------------------

/**
 * Ensure a MongoDB is reachable. Returns { ready, startedContainer }.
 * Tries: existing instance → throwaway Docker container → give up (skip).
 */
async function ensureMongo(): Promise<{ ready: boolean; startedContainer: boolean }> {
  if (await probeTcp(MONGO_HOST, MONGO_PORT)) {
    info(`MongoDB already reachable at ${MONGO_HOST}:${MONGO_PORT}`);
    return { ready: true, startedContainer: false };
  }
  if (!hasBinary('docker')) {
    warn(`No MongoDB on ${MONGO_HOST}:${MONGO_PORT} and Docker is not installed.`);
    return { ready: false, startedContainer: false };
  }
  info('Starting throwaway MongoDB container via Docker...');
  // Remove any leftover container from a previous aborted run.
  spawnSync('docker', ['rm', '-f', MONGO_CONTAINER], { stdio: 'ignore' });
  const start = spawnSync('docker', [
    'run', '-d', '--rm', '-p', `${MONGO_PORT}:27017`, '--name', MONGO_CONTAINER, 'mongo:7',
  ], { stdio: 'ignore' });
  if (start.status !== 0) {
    warn('Failed to start MongoDB container.');
    return { ready: false, startedContainer: false };
  }
  // Wait for it to accept connections.
  const deadline = Date.now() + 30_000;
  while (Date.now() < deadline) {
    if (await probeTcp(MONGO_HOST, MONGO_PORT)) {
      info('MongoDB container is ready.');
      return { ready: true, startedContainer: true };
    }
    await sleep(1000);
  }
  warn('MongoDB container did not become ready in time.');
  spawnSync('docker', ['rm', '-f', MONGO_CONTAINER], { stdio: 'ignore' });
  return { ready: false, startedContainer: false };
}

function stopMongoContainer(): void {
  spawnSync('docker', ['rm', '-f', MONGO_CONTAINER], { stdio: 'ignore' });
}

// ---------------------------------------------------------------------------
// The HTTP test flow (DB-agnostic)
// ---------------------------------------------------------------------------
async function runApiSuite(port: number): Promise<ReturnType<typeof makeSuite>> {
  const request = makeClient(port);
  const suite = makeSuite();

  const email = `e2e+${port}@example.com`;
  const password = 'Passw0rd!';

  // 1. Register / create user in DB
  const reg = await request('POST', '/users', {
    body: { email, password, firstName: 'E2E', lastName: 'Tester', phone: '5551234', role: 1 },
  });
  const regUser = (reg.body as AnyRecord)?.user;
  suite.check('POST /users registers a user (201 + token, no password)',
    reg.status === 201 && (reg.body as AnyRecord)?.accessToken && idOf(regUser) && !(regUser as AnyRecord)?.password,
    `status=${reg.status}`);
  const userId = idOf(regUser);

  // 2. Login
  const login = await request('POST', '/authentication', {
    body: { strategy: 'local', email, password },
  });
  const token = (login.body as AnyRecord)?.accessToken as string | undefined;
  suite.check('POST /authentication logs in (200 + token)',
    login.status === 200 && !!token, `status=${login.status}`);

  // 3. Verify token
  const verify = await request('GET', '/authentication/verify', { token });
  suite.check('GET /authentication/verify returns the user',
    verify.status === 200 && ((verify.body as AnyRecord)?.user as AnyRecord)?.email === email,
    `status=${verify.status}`);

  // 4. Guard rejects unauthenticated CRUD
  const unauth = await request('GET', `/${RESOURCE}`);
  suite.check(`GET /${RESOURCE} without token is rejected (401)`,
    unauth.status === 401, `status=${unauth.status}`);

  // 5. Create resource
  const created = await request('POST', `/${RESOURCE}`, { token, body: { name: 'Test Product' } });
  suite.check(`POST /${RESOURCE} creates a record (201 + id)`,
    created.status === 201 && idOf(created.body), `status=${created.status}`);
  const recordId = idOf(created.body);

  // 6. List
  const list = await request('GET', `/${RESOURCE}`, { token });
  suite.check(`GET /${RESOURCE} lists the created record`,
    list.status === 200 && asArray(list.body).some((r) => idOf(r) === recordId),
    `status=${list.status}`);

  // 7. Get one
  const getOne = await request('GET', `/${RESOURCE}/${recordId}`, { token });
  suite.check(`GET /${RESOURCE}/:id returns the record`,
    getOne.status === 200 && (getOne.body as AnyRecord)?.name === 'Test Product',
    `status=${getOne.status}`);

  // 8. Patch
  const patched = await request('PATCH', `/${RESOURCE}/${recordId}`, { token, body: { name: 'Updated' } });
  suite.check(`PATCH /${RESOURCE}/:id updates the record`,
    patched.status === 200 && (patched.body as AnyRecord)?.name === 'Updated', `status=${patched.status}`);

  // 9. Soft-delete
  const removed = await request('DELETE', `/${RESOURCE}/${recordId}`, { token });
  suite.check(`DELETE /${RESOURCE}/:id soft-deletes (2xx)`,
    removed.status >= 200 && removed.status < 300, `status=${removed.status}`);

  // 10. Confirm soft-delete hides the record
  const afterDelete = await request('GET', `/${RESOURCE}/${recordId}`, { token });
  const gone = afterDelete.status === 404 || afterDelete.body === null || afterDelete.body === '';
  suite.check(`GET /${RESOURCE}/:id no longer returns the deleted record`,
    gone, `status=${afterDelete.status}, body=${JSON.stringify(afterDelete.body)?.slice(0, 60)}`);

  // 11. List users includes the registered user
  const users = await request('GET', '/users', { token });
  suite.check('GET /users includes the registered user',
    users.status === 200 && asArray(users.body).some((u) => idOf(u) === userId),
    `status=${users.status}`);

  return suite;
}

// ---------------------------------------------------------------------------
// Per-DB run: generate → prep → boot → test → teardown
// ---------------------------------------------------------------------------
async function runForDatabase(db: DbType, port: number): Promise<RunResult> {
  const appName = `${db.toLowerCase()}-app`;
  const appDir = path.join(APPS_DIR, appName);
  const logPath = path.join(APPS_DIR, `${appName}.server.log`);

  heading(`Database: ${db}  (app: .e2e-apps/${appName}, port: ${port})`);

  // Fresh app dir each run, kept afterward.
  if (existsSync(appDir)) rmSync(appDir, { recursive: true, force: true });

  // 1. Generate app (cwd = APPS_DIR so the app lands inside .e2e-apps/)
  info(`Generating app with auth (${db})...`);
  await nestCli(['g', 'app', appName, '--db', db, '--validator', 'zod', '--pm', 'npm', '--auth'],
    { cwd: APPS_DIR });

  // 2. Generate CRUD resource (cwd = app dir)
  info(`Generating CRUD resource "${RESOURCE}"...`);
  await nestCli(['g', 'service', RESOURCE, '--db', db, '--validator', 'zod'], { cwd: appDir });

  // 3. DB prep (Prisma only)
  if (db !== 'Mongoose') {
    info('Generating Prisma client and pushing schema to SQLite...');
    await run('npx', ['prisma', 'generate'], { cwd: appDir });
    await run('npx', ['prisma', 'db', 'push'], { cwd: appDir });
  }

  // 4. Boot server
  info(`Starting server (logs → .e2e-apps/${appName}.server.log)...`);
  const server = startServer(appDir, port, logPath);
  let suite: ReturnType<typeof makeSuite> | undefined;
  try {
    const ready = await waitForServer(port, server, SERVER_READY_TIMEOUT_MS);
    if (!ready) {
      warn(`Server did not become ready within ${SERVER_READY_TIMEOUT_MS / 1000}s. See ${logPath}`);
      return { db, status: 'FAIL', reason: 'server not ready' };
    }
    info('Server ready. Running API assertions:');
    // 5. Run assertions
    suite = await runApiSuite(port);
  } finally {
    // 6. Teardown
    killServer(server);
    await sleep(500);
  }

  const failed = suite.failures.length;
  const status = failed === 0 ? 'PASS' : 'FAIL';
  return { db, status, passed: suite.total - failed, total: suite.total };
}

/**
 * Resolve how to invoke the generator. Prefers a globally-linked `nest-cli`;
 * otherwise falls back to the locally-built dist entry, building it on demand.
 * Sets the module-level `CLI`. Exits if it can't produce a runnable CLI.
 */
async function ensureCli(): Promise<void> {
  if (hasBinary('nest-cli')) {
    CLI = { cmd: 'nest-cli', prefix: [] };
    info('Using globally-linked nest-cli.');
    return;
  }
  if (!existsSync(DIST_CLI)) {
    info('nest-cli not linked — building the CLI from source (yarn nx build cli)...');
    try {
      await run('npx', ['nx', 'build', 'cli'], { cwd: REPO_ROOT });
    } catch {
      console.error(`${C.red}Failed to build the CLI. Run "yarn nx build cli" manually.${C.reset}`);
      process.exit(2);
    }
  }
  if (!existsSync(DIST_CLI)) {
    console.error(`${C.red}Built CLI not found at ${DIST_CLI}.${C.reset}`);
    process.exit(2);
  }
  CLI = { cmd: process.execPath, prefix: [DIST_CLI] };
  info(`Using locally-built CLI: ${path.relative(REPO_ROOT, DIST_CLI)}`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main(): Promise<void> {
  // Parse --db flag
  const args = process.argv.slice(2);
  let requested: string | null = null;
  const dbIdx = args.indexOf('--db');
  if (dbIdx !== -1 && args[dbIdx + 1]) requested = args[dbIdx + 1];

  const ALL: DbType[] = ['SQLite', 'Mongoose'];
  let matrix: DbType[] = ALL;
  if (requested) {
    const match = ALL.find((d) => d.toLowerCase() === requested!.toLowerCase());
    if (!match) {
      console.error(`${C.red}Unknown --db "${requested}". Valid: ${ALL.join(', ')}${C.reset}`);
      process.exit(2);
    }
    matrix = [match];
  }

  heading('NestExtended generated-app E2E test');

  // Resolve the generator: linked `nest-cli`, else the locally-built dist (built on demand).
  await ensureCli();

  mkdirSync(APPS_DIR, { recursive: true });

  const summary: RunResult[] = [];
  let port = 3100;
  let mongoStartedContainer = false;

  try {
    for (const db of matrix) {
      if (db === 'Mongoose') {
        const mongo = await ensureMongo();
        if (!mongo.ready) {
          warn('Skipping Mongoose run — no MongoDB available.');
          summary.push({ db, status: 'SKIP' });
          continue;
        }
        mongoStartedContainer = mongo.startedContainer;
      }
      try {
        const result = await runForDatabase(db, port);
        summary.push(result);
      } catch (err) {
        warn(`${db} run errored: ${(err as Error).message}`);
        summary.push({ db, status: 'FAIL', reason: (err as Error).message });
      }
      port += 1;
    }
  } finally {
    if (mongoStartedContainer) {
      info('Stopping MongoDB container...');
      stopMongoContainer();
    }
  }

  // Summary
  heading('Summary');
  let anyFail = false;
  for (const r of summary) {
    const counts = r.total !== undefined ? ` (${r.passed}/${r.total} checks)` : '';
    const reason = r.reason ? ` — ${r.reason}` : '';
    let color = C.green;
    if (r.status === 'FAIL') { color = C.red; anyFail = true; }
    else if (r.status === 'SKIP') color = C.yellow;
    log(`  ${color}${r.db}: ${r.status}${C.reset}${counts}${reason}`);
  }

  process.exit(anyFail ? 1 : 0);
}

main().catch((err) => {
  console.error(`${C.red}Unexpected error:${C.reset}`, err);
  process.exit(1);
});
